#!/bin/bash

function Help {
    cat <<HELP
Runs all of the NMT processing scripts. Resulting in alignment, skullstripping, segmentation, and
morphometrics for a given dsetume.

Usage:   
      NMT_subject_pipeline -i [input_dataset] -r [template_dset] <other options>

	where:
		input_dataset = the path of your dsetume in its original space.
		template_dset = the path of the template that you wish to align your data to.
	optional_arguments:	
		-a [segmentation/atlas_dset]: Warps a provided segmentation or atlas 
		     to the native space of the input_dataset
		-w [0*/1]: If 1, NMT_subject_align will "workhard" and spend extra time on the 
		     nonlinear alignment to improve results. Will significantly increase 
		     computational resources and time needed. (Default = 0)
		-b [1*/0]: If 1, runs antsBrainExtraction during NMT_subject_process (default)
		     If 0, warps the NMT brainmask back to the native subject. 
		     Simplier, but more reliable results.

Example:
   bash NMT_subject_pipeline -i macaque1+orig -r ../NMT.nii.gz

Dependencies:
		AFNI
		ANTs

HELP
    exit 1
}
segmentation=""
workhard=2
antsbrainextract=1
while getopts "h:i:r:a:w:b:" OPT
  do
  case $OPT in

      h) #help
	  echo "$Help"
	  exit 0
	  ;;
      i) #input
	  dset=$OPTARG
	  ;;
      r) #reference
	  template_dset=$OPTARG
	  ;;
      a) #segmentation/atlas dataset
	  segmentation=$OPTARG
	  ;;
      w) #workhard optiom
	  workhard=$OPTARG
	  ;;
      b) #antsBrainExtraction optiom
	  antsbrainextract=$OPTARG
	  ;;
      \?) # getopts issues an error message
	  Help >&2
	  exit 1
	  ;;
  esac
done
if [ -z "$dset" ]; then
	  Help >&2
	  exit 1
fi
if [ -z "$template_dset" ]; then
	  Help >&2
	  exit 1
fi

NMT_loc="$(cd "$(dirname "$0")" && pwd)"

pref=$(@GetAfniPrefix $dset)
pref=$(basename $pref .gz)
pref=$(basename $pref .nii)

#template_pref=$(@GetAfniPrefix $template_dset)
#template_pref=$(basename $template_pref .gz)
#template_pref=$(basename $template_pref .nii)
template_dir=$(dirname ${template_dset})
echo "	1) Change your current directory to ${template_dir}/single_subject_scans/${pref}/ "
	cp ${dset} ${template_dir}/tmp_$(basename ${dset})
	if [ ! -z "$segmentation" ]; then
		cp ${segmentation} ${template_dir}/tmp_$(basename ${segmentation})
	fi
	cd ${template_dir}

	if [ ! -d single_subject_scans/ ]; then
		mkdir single_subject_scans/
	fi

	cd single_subject_scans/

	if [ ! -d ${pref} ]; then
		mkdir ${pref}/
	else
		echo "ERROR: Scan directory already exists."
		echo "Please move conflicting directory or change your file name."
		exit
	fi

	cd ..

	dset=$(basename ${dset})
	cp tmp_${dset} single_subject_scans/${pref}/${dset}
	rm tmp_${dset}
	if [ ! -z "$segmentation" ]; then
		segmentation=$(basename ${segmentation})
		cp tmp_${segmentation} single_subject_scans/${pref}/${segmentation}
		rm tmp_${segmentation}
	fi
	cd single_subject_scans/${pref}/
	template_dset=../../$(basename ${template_dset})
echo "======================================================="

echo "	2) Align Single Subject Scan to the NIMH Macaque Template and align a given atlas to your single subject scan"
	if [ -z "$segmentation" ]; then
		echo bash ${NMT_loc}/NMT_subject_align -i ${dset} -r ${template_dset} -w ${workhard}
		bash ${NMT_loc}/NMT_subject_align -i ${dset} -r ${template_dset} -w ${workhard}
	else
		echo bash ${NMT_loc}/NMT_subject_align -i ${dset} -r ${template_dset} -a ${segmentation} -w ${workhard}
		bash ${NMT_loc}/NMT_subject_align -i ${dset} -r ${template_dset} -a ${segmentation} -w ${workhard}
		rm ${segmentation}
	fi
echo "======================================================="

echo "	3) Perform skull-striping and segmentation on you single subject dataset:"
	if [ -f ../../NMT_brainmask.nii.gz ] && [ -d ../../processing_masks/ ]; then
			echo bash ${NMT_loc}/NMT_subject_process ${dset} ${antsbrainextract}
			bash ${NMT_loc}/NMT_subject_process ${dset} ${antsbrainextract}
	else
		echo "NOTE: Relevant files for NMT_subject_process not found."
		echo "This either means that your template does not have the associated files"
		echo "or that your template has been moved away from its associated files."
		echo "SKIPPING NMT_subject_process"
		exit
	fi
echo "======================================================="

echo "	4) Estimate cortical thickness, surface area and curvature for single subject:"
	if [ -f ../../processing_masks/NMT_CT.nii.gz ] && [ -f ../../NMT_GM_cortical_mask.nii.gz ] && [ -f ../../NMT_GM_cortical_mask_withWM.nii.gz ]; then
		echo bash ${NMT_loc}/NMT_subject_morph ${dset}
		bash ${NMT_loc}/NMT_subject_morph ${dset}
	else
		echo "NOTE: Relevant files for NMT_subject_morph not found."
		echo "This either means that your template does not have the associated files"
		echo "or that your template has been moved away from its associated files."
		echo "SKIPPING NMT_subject_morph"
		exit
	fi
echo "======================================================="
