#!/bin/bash

function Help {
    cat <<HELP
Runs all of the NMT processing scripts. Resulting in alignment, skullstripping, segmentation, and
morphometrics for a given dsetume.

Usage:
      NMT_subject_pipeline -i [input_dataset] -o [output_directory] -r [template_dset] <other options>

	where:
		input_dataset = the path of your dset in its original space.
    output_directory = the path where all of your output files will be stored
		template_dset = the path of the template that you wish to align your data to.
	optional_arguments:
		-a [segmentation/atlas_dset]: Warps a provided segmentation or atlas
		     to the native space of the input_dataset
		-w [0*/1]: If 1, NMT_subject_align will "workhard" and spend extra time on the
		     nonlinear alignment to improve results. Will significantly increase
		     computational resources and time needed. (Default = 0)
		-b [1*/0]: If 1, runs antsBrainExtraction during NMT_subject_process (default)
		     If 0, warps the NMT brainmask back to the native subject.
		     Simplier, but more reliable results.

Example:
   bash NMT_subject_pipeline -i macaque1+orig -o single_subject_scans/macaque1/ -r ../NMT.nii.gz

Dependencies:
		AFNI
		ANTs

HELP
    exit 1
}
segmentation=""
workhard=2
antsbrainextract=1

while getopts "h:i:r:a:w:b:o:" OPT
  do
  case $OPT in

      h) #help
	  echo "$Help"
	  exit 0
	  ;;
      i) #input
	  dset=$OPTARG
	  ;;
      o) #outdir
    outdir=$OPTARG
    ;;
      r) #reference
	  template_dset=$OPTARG
	  ;;
      a) #segmentation/atlas dataset
	  segmentation=$OPTARG
	  ;;
      w) #workhard optiom
	  workhard=$OPTARG
	  ;;
      b) #antsBrainExtraction optiom
	  antsbrainextract=$OPTARG
	  ;;
      \?) # getopts issues an error message
	  Help >&2
	  exit 1
	  ;;
  esac
done
if [ -z "$dset" ]; then
    echo "Requires source volume"
	  Help >&2
	  exit 1
fi
if [ -z "$template_dset" ]; then
    echo "Requires target volume"
	  Help >&2
	  exit 1
fi
if [ -z "$outdir" ]; then
	  outdir=$(dirname ${template_dset})/single_subject_scans/$(basename ${dset})
fi

NMT_loc="$(cd "$(dirname "$0")" && pwd)"

pref=$(@GetAfniPrefix $dset)
pref=$(basename $pref .gz)
pref=$(basename $pref .nii)



#template_pref=$(@GetAfniPrefix $template_dset)
#template_pref=$(basename $template_pref .gz)
#template_pref=$(basename $template_pref .nii)
template_dir=$(dirname ${template_dset})
echo "	1) Change your current directory to ${outdir} "
  if [ ! -d ${outdir} ]; then
    mkdir -p ${outdir}
  fi

	cp ${dset} ${outdir}/$(basename ${dset})
  dset=$(basename ${dset})

	if [ ! -z "$segmentation" ]; then
		cp ${segmentation} ${outdir}/$(basename ${segmentation})
    segmentation=$(basename ${segmentation})
	fi

  cp ${template_dset} ${outdir}/$(basename ${template_dset})
  template_dset=$(basename ${template_dset})

	cd ${outdir}
echo "======================================================="

echo "	2) Align Single Subject Scan to the NIMH Macaque Template and align a given atlas to your single subject scan"
	if [ -z "$segmentation" ]; then
		echo bash ${NMT_loc}/NMT_subject_align -i ${dset} -r ${template_dset} -w ${workhard}
		bash ${NMT_loc}/NMT_subject_align -i ${dset} -r ${template_dset} -w ${workhard}
	else
		echo bash ${NMT_loc}/NMT_subject_align -i ${dset} -r ${template_dset} -a ${segmentation} -w ${workhard}
		bash ${NMT_loc}/NMT_subject_align -i ${dset} -r ${template_dset} -a ${segmentation} -w ${workhard}
		rm ${segmentation}
	fi
echo "======================================================="

echo "	3) Perform skull-striping and segmentation on you single subject dataset:"
	if [ -f ${NMT_loc}/NMT_brainmask.nii.gz ] && [ -d ${NMT_loc}/processing_masks/ ]; then
			echo bash ${NMT_loc}/NMT_subject_process ${dset} ${antsbrainextract}
			bash ${NMT_loc}/NMT_subject_process ${dset} ${antsbrainextract}
	else
		echo "NOTE: Relevant files for NMT_subject_process not found."
		echo "This either means that your template does not have the associated files"
		echo "or that your template has been moved away from its associated files."
		echo "SKIPPING NMT_subject_process"
		exit
	fi
echo "======================================================="

echo "	4) Estimate cortical thickness, surface area and curvature for single subject:"
	if [ -f ${NMT_loc}/processing_masks/NMT_CT.nii.gz ] && [ -f ${NMT_loc}/NMT_GM_cortical_mask.nii.gz ] && [ -f ${NMT_loc}/NMT_GM_cortical_mask_withWM.nii.gz ]; then
		echo bash ${NMT_loc}/NMT_subject_morph ${dset}
		bash ${NMT_loc}/NMT_subject_morph ${dset}
	else
		echo "NOTE: Relevant files for NMT_subject_morph not found."
		echo "This either means that your template does not have the associated files"
		echo "or that your template has been moved away from its associated files."
		echo "SKIPPING NMT_subject_morph"
		exit
	fi
echo "======================================================="
