#!/bin/bash
# Cortical thickness, surface area, and curvature estimates
# for individual subjects
#
# usage:
#       NMT_subject_morph [subject volume]
#
# dependencies:
#		ANTs
#		AFNI
#		Outputs of NMT_subject_align.csh
#
# nb: 
#		This script should be copied to the directory where the subject's 
#		anatomical volume lies --> which should be the directory of 
#		the output of NMT_subject_align 


# Assign the variable ANTSPATH where the ANTs installation lies
#export ANTSPATH=/usr/local/ANTs-1.9.v4-Linux/bin


# Extract name from subject volume file
name=$1
name=$(basename $name)
if [ "${name#*+*.}" = "HEAD" ] || [ "${name#*+*.}" = "BRIK" ]
	then
	echo "Converting ${name} to ${name[*]%+*.*}.nii.gz"
	3dcalc -a $name -expr 'a' -prefix ${name[*]%+*.*}.nii.gz -overwrite # Convert to nifti if needed
	name=${name[*]%+*.*}
fi
if [ "${name#*.}" = "nii.gz" ]
	then
	name=${name[*]%.*.*}
fi
if [ "${name#*.}" = "nii" ]
	then
	name=${name[*]%.*}
fi


# Make an output directory of NMT_subject_morph for the subject
mkdir NMT_${name}_morph
cd ./NMT_${name}_morph


## Optional log file
#exec 3>&1 4>&2
#trap 'exec 2>&4 1>&3' 0 1 2 3
#exec 1>NMT_${name}_morph_log.out 2>&1
## Everything below will go to the file '*_log.out':



# NMT_subject_morph pipeline:
# 0. Linearly align subject to NMT using rigid and affine transformations from NMT_subject_align
# 1. Non-linearly align NMT's GM cortical mask to subject
# 2. N4 Bias Field Correction on subject volume to eliminate non-uniformities in intensity values
# 3. Cortical thickness estimation with NMT CT mask as a prior using KellyKapowski over aligned (i.e. subject's) GM mask
# 4. Surface area and curvature estimation using SurfaceCurvature over subject's N4-corrected volume
# 5. Linearly transfrom all outputs back to native subject space

# Linearly align subject to NMT

3dAllineate -base ../../NMT.nii.gz -source ../${name}.nii.gz -1Dmatrix_apply ../${name}_shft.1D -master ../../NMT.nii.gz -prefix tmp.nii.gz -overwrite
3dAllineate -base ../../NMT.nii.gz -source ../${name}.nii.gz -1Dmatrix_apply ../${name}_shft_al2std_mat.aff12.1D -master ../../NMT.nii.gz -prefix tmp.nii.gz -overwrite

# Alignment of NMT's GM mask to subject

#cat_matvec ../${name}_shft.1D -I > tmp6.1D # create temporary inverse rigid-body transformation 
#cat_matvec ../${name}_shft_al2std_mat.aff12.1D -I > tmp12.1D # create temporary inverse affine transformation
#cat_matvec tmp6.1D tmp12.1D > tmpcat.1D # create temporary combined inverse transformation
3dNwarpApply -prefix ${name}_GM_cortical_mask.nii.gz ${name}_GM_cortical_mask_withWM.nii.gz ${name}_CT_prior.nii.gz -source ../../NMT_GM_cortical_mask.nii.gz ../../NMT_GM_cortical_mask_withWM.nii.gz ../../NMT_CT.nii.gz -master tmp.nii.gz -nwarp ../${name}_shft_WARPINV.nii.gz -ainterp NN -overwrite

# N4 intensity normalization over entire volume

$ANTSPATH/N4BiasFieldCorrection -d 3 -i tmp.nii.gz -o tmp.nii.gz -overwrite

# Cortical thickness estimation

$ANTSPATH/KellyKapowski -d 3 -s ${name}_GM_cortical_mask_withWM.nii.gz -t 5 -a ${name}_CT_prior.nii.gz -o ${name}_CT.nii.gz -v 1
rm ${name}_CT_prior.nii.gz

# Surface area estimation

$ANTSPATH/SurfaceCurvature tmp.nii.gz ${name}_SA.nii.gz 1 7

# Mean and intrinsic (Gaussian) curvature estimation

$ANTSPATH/SurfaceCurvature tmp.nii.gz ${name}_meancurv.nii.gz 1 0
$ANTSPATH/SurfaceCurvature tmp.nii.gz ${name}_gausscurv.nii.gz 1 6

# Transformation of generated masks and volumes from NMT to subject

#3dNwarpApply -prefix ${name}_GM_cortical_mask.nii.gz ${name}_CT.nii.gz ${name}_SA.nii.gz ${name}_meancurv.nii.gz ${name}_gausscurv.nii.gz -master $1 -nwarp tmp6.1D -ainterp NN -overwrite
3dAllineate -base ../$1 -source tmp.nii.gz -1Dmatrix_apply ${name}_shft_inv.aff12.1D -master ../$1 -prefix ${name}_N4.nii.gz -overwrite
3dAllineate -base ../$1 -source ${name}_N4.nii.gz -1Dmatrix_apply ${name}_shft_inv_shft.1D -final wsinc5 -prefix ${name}_N4.nii.gz -overwrite

3dAllineate -base ../$1 -source ${name}_GM_cortical_mask.nii.gz -1Dmatrix_apply ../${name}_shft_inv.aff12.1D -final NN -master ../$1 -prefix ${name}_GM_cortical_mask.nii.gz -overwrite
3dAllineate -base ../$1 -source ${name}_GM_cortical_mask.nii.gz -1Dmatrix_apply ../${name}_shft_inv_shft.1D -final NN -prefix ${name}_GM_cortical_mask.nii.gz -overwrite

3dAllineate -base ../$1 -source ${name}_GM_cortical_mask_withWM.nii.gz -1Dmatrix_apply ../${name}_shft_inv.aff12.1D -final NN -master ../$1 -prefix ${name}_GM_cortical_mask_withWM.nii.gz -overwrite
3dAllineate -base ../$1 -source ${name}_GM_cortical_mask_withWM.nii.gz -1Dmatrix_apply ../${name}_shft_inv_shft.1D -final NN -prefix ${name}_GM_cortical_mask_withWM.nii.gz -overwrite

3dAllineate -base ../$1 -source ${name}_CT.nii.gz -1Dmatrix_apply ../${name}_shft_inv.aff12.1D -final NN -master ../$1 -prefix ${name}_CT.nii.gz -overwrite
3dAllineate -base ../$1 -source ${name}_CT.nii.gz -1Dmatrix_apply ../${name}_shft_inv_shft.1D -final NN -prefix ${name}_CT.nii.gz -overwrite

3dAllineate -base ../$1 -source ${name}_SA.nii.gz -1Dmatrix_apply ../${name}_shft_inv.aff12.1D -final NN -master ../$1 -prefix ${name}_SA.nii.gz -overwrite
3dAllineate -base ../$1 -source ${name}_SA.nii.gz -1Dmatrix_apply ../${name}_shft_inv_shft.1D -final NN -prefix ${name}_SA.nii.gz -overwrite

3dAllineate -base ../$1 -source ${name}_meancurv.nii.gz -1Dmatrix_apply ../${name}_shft_inv.aff12.1D -final NN -master ../$1 -prefix ${name}_meancurv.nii.gz -overwrite
3dAllineate -base ../$1 -source ${name}_meancurv.nii.gz -1Dmatrix_apply ../${name}_shft_inv_shft.1D -final NN -prefix ${name}_meancurv.nii.gz -overwrite

3dAllineate -base ../$1 -source ${name}_gausscurv.nii.gz -1Dmatrix_apply ../${name}_shft_inv.aff12.1D -final NN -master ../$1 -prefix ${name}_gausscurv.nii.gz -overwrite
3dAllineate -base ../$1 -source ${name}_gausscurv.nii.gz -1Dmatrix_apply ../${name}_shft_inv_shft.1D -final NN -prefix ${name}_gausscurv.nii.gz -overwrite
rm tmp.nii.gz
#rm -r tmp*.1D





