#!/bin/bash
# Brain extraction, N4 intensity normalization, and tissue segmentation
# for individual subjects using the NMT priors
#
# usage:
#       NMT_subject_process [subject volume] [space=ORIG/NMT] [log=0/1] [mask_gen_method=ANTs/NMT_warp]
#
# dependencies:
#		ANTs
#		AFNI
#		Outputs of NMT_subject_align.csh
#
# nb: 
#		This script should be copied to the directory where the subject's 
#		anatomical volume lies --> which should be the directory of 
#		the output of NMT_subject_align 


# Assign the variable ANTSPATH where the ANTs installation lies
#export ANTSPATH=/usr/local/ANTs-1.9.v4-Linux/bin


# Extract name from subject volume file
name=$1
name=$(basename $name)
if [ "${name#*+*.}" = "HEAD" ] || [ "${name#*+*.}" = "BRIK" ]
	then
	echo "Converting ${name} to ${name[*]%+*.*}.nii.gz"
	3dcalc -a $name -expr 'a' -prefix ${name[*]%+*.*}.nii.gz -overwrite # Convert to nifti if needed
	name=${name[*]%+*.*}
fi
if [ "${name#*.}" = "nii.gz" ]
	then
	name=${name[*]%.*.*}
fi
if [ "${name#*.}" = "nii" ]
	then
	name=${name[*]%.*}
fi
space=${2:-ORIG}
log=${3:-0}
mask_gen_method=${4:-ANTs}

# Make an output directory of NMT_subject_process for the subject
mkdir NMT_${name}_process
cd ./NMT_${name}_process


## Optional log file
if [ "$log" = 1 ]
	then
	exec 3>&1 4>&2
	trap 'exec 2>&4 1>&3' 0 1 2 3
	exec 1>NMT_${name}_process_log.out 2>&1
	## Everything below will go to the file '*_log.out':
fi


# NMT_subject_process pipeline:
# 0. Acquire linearly align subject to NMT from NMT_subject_align
# 1. 1st N4 intensity normalization over entire volume
# 2. Brain extraction using antsBrainExtraction.sh
# 3. 2nd N4 intensity normalization and Atropos tissue segmentation
# 4. Rigidly transfrom all outputs back to native subject space

# 0. Acquire linearly align subject to NMT from NMT_subject_align
3dcalc -a ../${name}_shft_aff+orig -expr 'a' -prefix ../${name}_shft_aff.nii.gz

# N4 intensity normalization over entire volume

$ANTSPATH/N4BiasFieldCorrection -d 3 -i ../${name}_shft_aff.nii.gz -o ${name}_N4.nii.gz

# Brain extraction
if [ "$log" = ANTs ]
then
	$ANTSPATH/antsBrainExtraction.sh -d 3 -a ${name}_N4.nii.gz -e ../../NMT.nii.gz -m ../../NMT_brainmask.nii.gz -o ${name}_

	rm -r ${name}_ # remove directory that ANTs makes
	cp ${name}_BrainExtractionBrain.nii.gz ${name}_brain.nii.gz # change filenames 
	cp ${name}_BrainExtractionMask.nii.gz ${name}_brainmask.nii.gz # change filenames 
	rm ${name}_BrainExtractionBrain.nii.gz # remove default ANTs outputs
	rm ${name}_BrainExtractionMask.nii.gz # remove default ANTs outputs
elif [ "$log" = NMT_warp ]
then
	3dNwarpApply -prefix ${name}_brainmask.nii.gz -source ../../NMT_brainmask.nii.gz -master ../${name}_shft_aff.nii.gz -nwarp ../${name}_shft_WARPINV.nii.gz -ainterp NN -overwrite
	3dcalc -a ${name}_N4.nii.gz -b ${name}_brainmask.nii.gz -expr 'a*b' -prefix ${name}_brain.nii.gz
fi


# Tissue segmentation

cp ../../NMT_segmentation_CSF.nii.gz tmp_01.nii.gz # create temporary NMT probabilistic segmentation files which ANTs can read as priors 
cp ../../NMT_segmentation_GM.nii.gz tmp_02.nii.gz
cp ../../NMT_segmentation_WM.nii.gz tmp_03.nii.gz

$ANTSPATH/antsAtroposN4.sh -d 3 -a ${name}_N4.nii.gz -x ${name}_brainmask.nii.gz -c 3 -p tmp_%02d.nii.gz -o ${name}_segmentation_

cp ${name}_segmentation_SegmentationPosteriors01.nii.gz ${name}_segmentation_CSF.nii.gz # change filenames
cp ${name}_segmentation_SegmentationPosteriors02.nii.gz ${name}_segmentation_GM.nii.gz # change filenames
cp ${name}_segmentation_SegmentationPosteriors03.nii.gz ${name}_segmentation_WM.nii.gz # change filenames
cp ${name}_segmentation_Segmentation.nii.gz ${name}_segmentation.nii.gz # change filenames
rm -r ${name}_segmentation_SegmentationPosteriors*.nii.gz # remove default ANTs outputs
rm -r ${name}_segmentation_ # remove default ANTs outputs
rm -r tmp_*.nii.gz # remove temporary NMT segmentation priors
rm -r ${name}_segmentation_Segmentation0N4.nii.gz
rm -r ${name}_N4Truncated0.nii.gz

# Transformation of generated masks and volumes from NMT to subject

if [ "$space" = "ORIG" ]
	then
	echo "Warping results back to native space"

	cat_matvec ../${name}_shft_inv.aff12.1D ../${name}_inv_shft.1D -ONELINE > tmp_inv_linear.1D

	3dAllineate -base ../$1 -source ${name}_N4.nii.gz -1Dmatrix_apply tmp_inv_linear.1D -prefix ${name}_N4.nii.sgz -overwrite

	3dAllineate -base ../$1 -source ${name}_brain.nii.gz -1Dmatrix_apply tmp_inv_linear.1D -prefix ${name}_brain.nii.gz -overwrite

	3dAllineate -base ../$1 -source ${name}_brainmask.nii.gz -1Dmatrix_apply tmp_inv_linear.1D -prefix ${name}_brainmask.nii.gz -overwrite

	3dAllineate -base ../$1 -source ${name}_segmentation.nii.gz -1Dmatrix_apply tmp_inv_linear.1D -final NN -prefix ${name}_segmentation.nii.gz -overwrite

	3dAllineate -base ../$1 -source ${name}_segmentation_CSF.nii.gz -1Dmatrix_apply tmp_inv_linear.1D -final NN -prefix ${name}_segmentation_CSF.nii.gz -overwrite

	3dAllineate -base ../$1 -source ${name}_segmentation_GM.nii.gz -1Dmatrix_apply tmp_inv_linear.1D -final NN -prefix ${name}_segmentation_GM.nii.gz -overwrite

	3dAllineate -base ../$1 -source ${name}_segmentation_WM.nii.gz -1Dmatrix_apply tmp_inv_linear.1D -final NN -prefix ${name}_segmentation_WM.nii.gz -overwrite
fi

rm -r tmp*.1D # remove temporary inverse warp files 




