#!/bin/bash
# Brain extraction, N4 intensity normalization, and tissue segmentation
# for individual subjects using the NMT priors
#
# usage:
#       NMT_subject_process [subject volume]
#
# dependencies:
#		ANTs
#		AFNI
#		Outputs of NMT_subject_align.csh
#
# nb: 
#		This script should be copied to the directory where the subject's 
#		anatomical volume lies --> which should be the directory of 
#		the output of NMT_subject_align 


# Assign the variable ANTSPATH where the ANTs installation lies
#export ANTSPATH=/usr/local/ANTs-1.9.v4-Linux/bin


# Extract name from subject volume file
name=$1
name=$(basename $name)
if [ "${name#*+*.}" = "HEAD" ] || [ "${name#*+*.}" = "BRIK" ]
	then
	echo "Converting ${name} to ${name[*]%+*.*}.nii.gz"
	3dcalc -a $name -expr 'a' -prefix ${name[*]%+*.*}.nii.gz -overwrite # Convert to nifti if needed
	name=${name[*]%+*.*}
fi
if [ "${name#*.}" = "nii.gz" ]
	then
	name=${name[*]%.*.*}
fi
if [ "${name#*.}" = "nii" ]
	then
	name=${name[*]%.*}
fi


# Make an output directory of NMT_subject_process for the subject
mkdir NMT_${name}_process
cd ./NMT_${name}_process


## Optional log file
#exec 3>&1 4>&2
#trap 'exec 2>&4 1>&3' 0 1 2 3
#exec 1>NMT_${name}_process_log.out 2>&1
## Everything below will go to the file '*_log.out':



# NMT_subject_process pipeline:
# 0. Linearly align subject to NMT
# 1. 1st N4 intensity normalization over entire volume
# 2. Brain extraction using antsBrainExtraction.sh
# 3. 2nd N4 intensity normalization and Atropos tissue segmentation
# 4. Rigidly transfrom all outputs back to native subject space

# Linear aligment of subject's anatomical volume using the 6- and 12-parameter tranformation files from NMT_subject_align

3dAllineate -base ../../NMT.nii.gz -source ../${name}.nii.gz -1Dmatrix_apply ../${name}_shft.1D -prefix tmp.nii.gz -overwrite
3dAllineate -base ../../NMT.nii.gz -source ../${name}.nii.gz -1Dmatrix_apply ../${name}_shft_al2std_mat.aff12.1D -prefix tmp.nii.gz -overwrite

# N4 intensity normalization over entire volume

$ANTSPATH/N4BiasFieldCorrection -d 3 -i tmp.nii.gz -o ${name}_N4.nii.gz
rm tmp.nii.gz

# Brain extraction


rm -r ${name}_ # remove directory that ANTs makes
cp ${name}_BrainExtractionBrain.nii.gz ${name}_brain.nii.gz # change filenames 
cp ${name}_BrainExtractionMask.nii.gz ${name}_brainmask.nii.gz # change filenames 
rm ${name}_BrainExtractionBrain.nii.gz # remove default ANTs outputs
rm ${name}_BrainExtractionMask.nii.gz # remove default ANTs outputs

# Tissue segmentation

cp ../../NMT_segmentation_CSF.nii.gz tmp_01.nii.gz # create temporary NMT probabilistic segmentation files which ANTs can read as priors 
cp ../../NMT_segmentation_GM.nii.gz tmp_02.nii.gz
cp ../../NMT_segmentation_WM.nii.gz tmp_03.nii.gz

$ANTSPATH/antsAtroposN4.sh -d 3 -a ${name}_N4.nii.gz -x ${name}_brainmask.nii.gz -c 3 -p tmp_%02d.nii.gz -o ${name}_segmentation_

cp ${name}_segmentation_SegmentationPosteriors01.nii.gz ${name}_segmentation_CSF.nii.gz # change filenames
cp ${name}_segmentation_SegmentationPosteriors02.nii.gz ${name}_segmentation_GM.nii.gz # change filenames
cp ${name}_segmentation_SegmentationPosteriors03.nii.gz ${name}_segmentation_WM.nii.gz # change filenames
cp ${name}_segmentation_Segmentation.nii.gz ${name}_segmentation.nii.gz # change filenames
rm -r ${name}_segmentation_SegmentationPosteriors*.nii.gz # remove default ANTs outputs
rm -r ${name}_segmentation_ # remove default ANTs outputs
rm -r tmp_*.nii.gz # remove temporary NMT segmentation priors
rm -r ${name}_segmentation_Segmentation0N4.nii.gz
rm -r ${name}_N4Truncated0.nii.gz

# Transformation of generated masks and volumes from NMT to subject

#cat_matvec ../${name}_shft.1D -I > tmp6.1D # create temporary inverse rigid-body transformation
#cat_matvec ../${name}_shft_al2std_mat.aff12.1D -I > tmp12.1D # create temporary inverse affine transformation
#3dNwarpApply -prefix ${name}_N4.nii.gz ${name}_brain.nii.gz ${name}_brainmask.nii.gz ${name}_segmentation.nii.gz ${name}_segmentation_CSF.nii.gz ${name}_segmentation_GM.nii.gz ${name}_segmentation_WM.nii.gz -source ${name}_N4.nii.gz ${name}_brain.nii.gz ${name}_brainmask.nii.gz ${name}_segmentation.nii.gz ${name}_segmentation_CSF.nii.gz ${name}_segmentation_GM.nii.gz ${name}_segmentation_WM.nii.gz -master ../$1 -nwarp '../${name}_shft_al2std_mat.aff12.1D ../../${name}_shft_WARP.nii.gz ../../${name}_shft_INVWARP.nii.gz tmp12.1D tmp6.1D' -ainterp NN -overwrite
3dAllineate -base ../$1 -source ${name}_N4.nii.gz -1Dmatrix_apply ../${name}_shft_inv.aff12.1D -prefix ${name}_N4.nii.gz -overwrite
3dAllineate -base ../$1 -source ${name}_N4.nii.gz -1Dmatrix_apply ../${name}_inv_shft.1D -prefix ${name}_N4.nii.gz -overwrite

3dAllineate -base ../$1 -source ${name}_brain.nii.gz -1Dmatrix_apply ../${name}_shft_inv.aff12.1D -prefix ${name}_brain.nii.gz -overwrite
3dAllineate -base ../$1 -source ${name}_brain.nii.gz -1Dmatrix_apply ../${name}_inv_shft.1D -prefix ${name}_brain.nii.gz -overwrite

3dAllineate -base ../$1 -source ${name}_brainmask.nii.gz -1Dmatrix_apply ../${name}_shft_inv.aff12.1D -prefix ${name}_brainmask.nii.gz -overwrite
3dAllineate -base ../$1 -source ${name}_brainmask.nii.gz -1Dmatrix_apply ../${name}_inv_shft.1D -prefix ${name}_brainmask.nii.gz -overwrite

3dAllineate -base ../$1 -source ${name}_segmentation.nii.gz -1Dmatrix_apply ../${name}_shft_inv.aff12.1D -final NN -prefix ${name}_segmentation.nii.gz -overwrite
3dAllineate -base ../$1 -source ${name}_segmentation.nii.gz -1Dmatrix_apply ../${name}_inv_shft.1D -final NN -prefix ${name}_segmentation.nii.gz -overwrite

3dAllineate -base ../$1 -source ${name}_segmentation_CSF.nii.gz -1Dmatrix_apply ../${name}_shft_inv.aff12.1D -final NN -prefix ${name}_segmentation_CSF.nii.gz -overwrite
3dAllineate -base ../$1 -source ${name}_segmentation_CSF.nii.gz -1Dmatrix_apply ../${name}_inv_shft.1D -final NN -prefix ${name}_segmentation_CSF.nii.gz -overwrite

3dAllineate -base ../$1 -source ${name}_segmentation_GM.nii.gz -1Dmatrix_apply ../${name}_shft_inv.aff12.1D -final NN -prefix ${name}_segmentation_GM.nii.gz -overwrite
3dAllineate -base ../$1 -source ${name}_segmentation_GM.nii.gz -1Dmatrix_apply ../${name}_inv_shft.1D -final NN -prefix ${name}_segmentation_GM.nii.gz -overwrite

3dAllineate -base ../$1 -source ${name}_segmentation_WM.nii.gz -1Dmatrix_apply ../${name}_shft_inv.aff12.1D -final NN -prefix ${name}_segmentation_WM.nii.gz -overwrite
3dAllineate -base ../$1 -source ${name}_segmentation_WM.nii.gz -1Dmatrix_apply ../${name}_inv_shft.1D -final NN -prefix ${name}_segmentation_WM.nii.gz -overwrite
rm -r tmp*.1D # remove temporary inverse warp files 





